### ISSUE TITLE
비명 탐지 프로젝트에  demo.py 가 없습니다.

### ISSUE THREAD

**Issue by choidong** [deep-learning-with-projects/deep-learning-with-projects#11]
프로젝트 파일에 demo.py 가 누락되어 있습니다. 확인 부탁드립니다.

**Comment by hunhoon21** [comment]
안녕하세요, @choidong 님. 답변이 늦어 많이 죄송하다는 말씀부터 전달드립니다.
저희가 2개의 채널을 다루다 해당 repository에 올라온 이슈를 인지하지 못했습니다. 출판사 깃허브에도 같은 이슈가 올라와 임시로 파일 소스코드를 올려두었는데, 이곳에는 미처 올려두지 못했습니다.

잠시동안 git-lfs bandwidth 이슈로 해당 repository에 git 작업을 할 수 없었습니다.
해결 후 `demo.py` 와 데모를 돌리는데 필요한 ui 파일인 `22.ui` 파일을 추가로 업로드 해두었으니, 확인 부탁드립니다.

감사합니다.

**Comment by hunhoon21** [comment]
추가 업로드 후 20일이 지나 close 하겠습니다.
