### ISSUE TITLE
전체적으로 데이터셋을 모아서 정리해주면 좋겠습니다.

### ISSUE THREAD

**Issue by sehungen** [deep-learning-with-projects/deep-learning-with-projects#12]
라인단위의 코멘트나 다양한 데이터 타입의 프로젝트를 다루는 컨셉이 좋았는데 주변에 추천하기에는 아쉬운 점이 있습니다.
각 챕터마다 저자가 달라서 코드스타일이 다른 건 바빠서 그럴 수 있다고 하지만 데이터셋을 제공하지 않는 건 이해가 되지 않네요.
출판사가 듣보라서 그런건지, 아니면 쓰기싫은 책 억지로 쓰다보니 그런건지 모르겠는데 몇몇 챕터 때문에 책의 수준이 떨어져 보여서 아쉽네요.

**Comment by hunhoon21** [comment]
@sehungen 안녕하세요, 세훈님.
먼저 솔직한 피드백을 전해주셔서 감사하고, 데이터셋 이슈로 불편하게 만들어 죄송하다는 말씀 또한 전달 드립니다.

저희가 예기치 못했던 git-lfs 문제로 일부 파일들이 누락이 되는 이슈가 있었습니다. 그리고 말씀처럼 데이터셋 정보를 README 에 작성하는것을 놓친 일부 프로젝트도 있었습니다.
최근에 모두 수정했으니 확인 부탁드립니다.

다시 한 번 피드백 감사드립니다.

**Comment by hunhoon21** [comment]
데이터셋 설명이 추가되어 close 하도록 하겠습니다.
